# Generated by Django 5.2.7 on 2025-10-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_booking_tickettype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='senior_tickets',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='adult_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
